version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "4000:8080"
    volumes: 
      - ./jenkins_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    
    restart: unless-stopped
    
    networks: 
      - net

networks: 
  net: 
